### ISSUE TITLE
Make message edit and delete embeds able to handle message with up to 4000 characters

### ISSUE THREAD

**Issue by ajax146** [r-Techsupport/TechSupportBot#101]
4000 characters is the max on discord, only reachable with someone with nitro.

The current system fails > 1024 characters.
The embed needs to be redone to handle larger messages.

**Comment by TheKrol** [comment]
![image](https://user-images.githubusercontent.com/7559922/210682937-b049608d-b372-4bc1-97f2-d3723f3768e5.png)
Edit can handle 4000 characters
