### ISSUE TITLE
Make a nicer error on ban/kick failure

### ISSUE THREAD

**Issue by ajax146** [r-Techsupport/TechSupportBot#197]
If a ban/kick command is attempted, check to see if the bot user (in addition to the invoker) has permission to ban/kick that user.
If not, make a nicer-looking error, saying the bot doesn't have the correct permissions.

Currently, the error is:
I ran into an error processing your command: Command raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

**Comment by TheKrol** [comment]
I believe this should've been fixed with the unban changes.

**Comment by Cpt-Dingus** [comment]
Isn't fixed in current build, looking into this tonight.
