### ISSUE TITLE
The confirm function needs handing for what happens if deny

### ISSUE THREAD

**Issue by ajax146** [r-Techsupport/TechSupportBot#330]
Currently, there is logic to determine whether to delete the confirm function.
Nothing will happen if no is selected and delete is false (the default), and the confirm message will stay on the screen.

Changes that should be made:
The default becomes delete of true
And, if the confirmation is no, an acknowledgement message is sent.

This is context.py - Confirm function

**Comment by Cpt-Dingus** [comment]
Looking at this, I got two questions:
1) "The default of delete becomes true" What's the reason for this?
2) What do you want the acknowledgement message to look like? I'd personally do with a reaction added to the initial confirm command
