### ISSUE TITLE
Add a thank you plugin

### ISSUE THREAD

**Issue by TSBots** [r-Techsupport/TechSupportBot#8]
Look for thank yous in the chat, and record thank you stats

**Comment by Cpt-Dingus** [comment]
How would this work? The people they were responding to or pinging would get logged, making this a pseudo-reputation system?

**Comment by Cpt-Dingus** [comment]
@ajax146 Gotcha, though I do not have the perms to close the issues

**Comment by Cpt-Dingus** [comment]
The closest thing I can think of is a .rep command, but that does not fit the whole r/TS mo. There is no other reliable way to do this, in case someone wants to make a .rep anyways go ahead and make a separate issue for it.

**Comment by Cpt-Dingus** [comment]
Closing
