### ISSUE TITLE
Add role logging

### ISSUE THREAD

**Issue by ajax146** [r-Techsupport/TechSupportBot#98]
Role logging used to exist in TS, not sure what happened to it (maybe it's just broken).

Adding back when people gain or lose roles would be good.

**Comment by TheKrol** [comment]
![image](https://user-images.githubusercontent.com/7559922/210683040-ba4250b7-2a9a-468c-b481-ee3fd35335a6.png)
![image](https://user-images.githubusercontent.com/7559922/210683071-f0dc9e5a-def6-4514-a427-652342e0f636.png)

**Comment by TheKrol** [comment]
`async def on_member_update(self, before, after):
        """See: https://discordpy.readthedocs.io/en/latest/api.html#discord.on_member_update"""
        changed_role = set(before.roles) ^ set(after.roles)
        if len(before.roles) < len(after.roles):               
            embed = discord.Embed()
            embed.add_field(name="Roles added", value=next(iter(changed_role)))
            embed.add_field(name="Server", value=before.guild.name)
        else:
            embed = discord.Embed()
            embed.add_field(name="Roles lost", value=next(iter(changed_role)))
            embed.add_field(name="Server", value=before.guild.name)
            
        log_channel = await self.get_log_channel_from_guild(
            getattr(before, "guild", None), key="member_events_channel"
        )
        
        await self.logger.info(
            f"Member with ID `{before.id}` has changed status in guild with ID {before.guild.id}",
            embed=embed,
            send=True,
            channel=log_channel,
        )`
